services:
  - type: web
    name: punchonline
    env: python
    plan: free

    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install --with-deps chromium

    startCommand: gunicorn app:app